# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "home-task-ci" ]
  pull_request:
    branches: [ "home-task-ci" ]
env: 
    FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v2
      - name: Install dependencies
        run: flutter pub get
      - name: Build runner build
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Firebase setup
        run: curl -sL https://firebase.tools | bash
      - run: dart pub global activate flutterfire_cli
      - run: export PATH="$PATH":"$HOME/.pub-cache/bin"
      - run: firebase deploy --token "env.FIREBASE_TOKEN"
      - run: flutterfire configure --token=env.FIREBASE_TOKEN --project="todo-yandex-flutter" 
             --platforms="android" 
             --ios-bundle-id="todo-yandex-flutter" 
             --android-package-name="todo-yandex-flutter" --yes 
             
      - run: flutterfire config --android-app-id=com.example.to_do_yandex.dev
      - run: flutter pub get

             

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run get
        run: flutter pub get 
             
      - name: Run analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
